# Generated by Django 4.1 on 2022-09-07 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('whatsapp_link', models.URLField(null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('phone_number_2', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('status', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Guest wing', 'Guest wing')], max_length=200, null=True)),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(null=True)),
                ('house_number', models.CharField(max_length=50, null=True)),
                ('garages', models.PositiveSmallIntegerField(null=True)),
                ('house_images', models.ImageField(null=True, upload_to='house_images/')),
                ('area', models.FloatField(null=True)),
                ('district', models.CharField(choices=[('Lilongwe', 'Lilongwe'), ('Blantyre', 'Blantyre'), ('Zomba', 'Zomba'), ('Mzuzu', 'Mzuzu'), ('Salima', 'Salima'), ('Mangochi', 'Mangochi'), ('Mulanje', 'Mulanje'), ('Mzimba', 'Mzimba'), ('Dedza', 'Dedza'), ('Dowa', 'Dowa'), ('Machinga', 'Machinga'), ('Balaka', 'Balaka'), ('Chikhwawa', 'Chikhwawa'), ('Kasungu', 'Kasungu'), ('Thyolo', 'Thyolo'), ('Phalombe', 'Phalombe'), ('Rumphi', 'Rumphi'), ('Chitipa', 'Chitipa'), ('Neno', 'Neno'), ('Nsanje', 'Nsanje'), ('chiradzulu', 'Chiradzulu'), ('Karonga', 'Karonga'), ('Nkhata-Bay', 'Nkhata-Bay'), ('Nkhotakota', 'Nkhotakota'), ('Ntchisi', 'Ntchisi'), ('Ntcheu', 'Ntcheu'), ('Mchinji', 'Mchinji'), ('Mwanza', 'Mwanza')], max_length=100, null=True)),
                ('property_authentication', models.FileField(null=True, upload_to='')),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('image_2', models.ImageField(null=True, upload_to='house_images/')),
                ('image_3', models.ImageField(null=True, upload_to='house_images/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
