# Generated by Django 3.2 on 2021-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whats_app_link',
            field=models.URLField(null=True),
        ),
    ]
