# Generated by Django 3.2 on 2021-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211021_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, default=True, max_length=100),
        ),
    ]
